import type { Sentence } from "../domain/sentence";

/**
 * The built-in beginner sentences: subject + verb + complement, three tiles
 * each, reusing pack vocabulary wherever possible so the words are familiar.
 */
export const SENTENCE_PACK: readonly Sentence[] = [
  {
    id: "gato-negro",
    tokens: ["el gato", "es", "negro"],
    english: "the cat is black",
    emoji: "🐱",
  },
  {
    id: "rana-verde",
    tokens: ["la rana", "es", "verde"],
    english: "the frog is green",
    emoji: "🐸",
  },
  {
    id: "elefante-grande",
    tokens: ["el elefante", "es", "grande"],
    english: "the elephant is big",
    emoji: "🐘",
  },
  {
    id: "manzana-roja",
    tokens: ["la manzana", "es", "roja"],
    english: "the apple is red",
    emoji: "🍎",
  },
  {
    id: "platano-amarillo",
    tokens: ["el plátano", "es", "amarillo"],
    english: "the banana is yellow",
    emoji: "🍌",
  },
  {
    id: "mariposa-bonita",
    tokens: ["la mariposa", "es", "bonita"],
    english: "the butterfly is pretty",
    emoji: "🦋",
  },
  {
    id: "perro-pan",
    tokens: ["el perro", "come", "pan"],
    english: "the dog eats bread",
    emoji: "🐶",
  },
  {
    id: "gato-leche",
    tokens: ["el gato", "bebe", "leche"],
    english: "the cat drinks milk",
    emoji: "🥛",
  },
  {
    id: "vaca-hierba",
    tokens: ["la vaca", "come", "hierba"],
    english: "the cow eats grass",
    emoji: "🐮",
  },
  {
    id: "pez-nada",
    tokens: ["el pez", "nada", "rápido"],
    english: "the fish swims fast",
    emoji: "🐟",
  },
  {
    id: "caballo-corre",
    tokens: ["el caballo", "corre", "rápido"],
    english: "the horse runs fast",
    emoji: "🐴",
  },
  {
    id: "pajaro-alto",
    tokens: ["el pájaro", "vuela", "alto"],
    english: "the bird flies high",
    emoji: "🐦",
  },
  {
    id: "sol-amarillo",
    tokens: ["el sol", "es", "amarillo"],
    english: "the sun is yellow",
    emoji: "☀️",
  },
  {
    id: "nieve-blanca",
    tokens: ["la nieve", "es", "blanca"],
    english: "the snow is white",
    emoji: "❄️",
  },
  {
    id: "mar-azul",
    tokens: ["el mar", "es", "azul"],
    english: "the sea is blue",
    emoji: "🌊",
  },
  {
    id: "veo-luna",
    tokens: ["yo", "veo", "la luna"],
    english: "I see the moon",
    emoji: "🌙",
  },
  {
    id: "coche-rapido",
    tokens: ["el coche", "es", "rápido"],
    english: "the car is fast",
    emoji: "🚗",
  },
  {
    id: "tren-grande",
    tokens: ["el tren", "es", "grande"],
    english: "the train is big",
    emoji: "🚂",
  },
  {
    id: "avion-alto",
    tokens: ["el avión", "vuela", "alto"],
    english: "the airplane flies high",
    emoji: "✈️",
  },
  {
    id: "camiseta-roja",
    tokens: ["la camiseta", "es", "roja"],
    english: "the t-shirt is red",
    emoji: "👕",
  },
  {
    id: "mano-pequena",
    tokens: ["la mano", "es", "pequeña"],
    english: "the hand is small",
    emoji: "🖐️",
  },
  {
    id: "duermo-cama",
    tokens: ["yo", "duermo", "en la cama"],
    english: "I sleep in the bed",
    emoji: "🛏️",
  },
  {
    id: "lluvia-fria",
    tokens: ["la lluvia", "es", "fría"],
    english: "the rain is cold",
    emoji: "🌧️",
  },
  {
    id: "helado-frio",
    tokens: ["el helado", "es", "frío"],
    english: "the ice cream is cold",
    emoji: "🍦",
  },
  {
    id: "arbol-verde",
    tokens: ["el árbol", "es", "verde"],
    english: "the tree is green",
    emoji: "🌳",
  },
  {
    id: "fuego-caliente",
    tokens: ["el fuego", "es", "caliente"],
    english: "the fire is hot",
    emoji: "🔥",
  },
  {
    id: "montana-alta",
    tokens: ["la montaña", "es", "alta"],
    english: "the mountain is tall",
    emoji: "⛰️",
  },
  {
    id: "juego-pelota",
    tokens: ["yo", "juego", "con la pelota"],
    english: "I play with the ball",
    emoji: "⚽",
  },
  {
    id: "robot-baila",
    tokens: ["el robot", "baila", "bien"],
    english: "the robot dances well",
    emoji: "🤖",
  },
  {
    id: "leo-libro",
    tokens: ["yo", "leo", "el libro"],
    english: "I read the book",
    emoji: "📕",
  },
  {
    id: "estoy-feliz",
    tokens: ["yo", "estoy", "feliz"],
    english: "I am happy",
    emoji: "😀",
  },
  {
    id: "gato-dormido",
    tokens: ["el gato", "está", "dormido"],
    english: "the cat is asleep",
    emoji: "😴",
  },
  {
    id: "toco-guitarra",
    tokens: ["yo", "toco", "la guitarra"],
    english: "I play the guitar",
    emoji: "🎸",
  },
  {
    id: "nado-mar",
    tokens: ["yo", "nado", "en el mar"],
    english: "I swim in the sea",
    emoji: "🌊",
  },
  {
    id: "flor-bonita",
    tokens: ["la flor", "es", "bonita"],
    english: "the flower is pretty",
    emoji: "🌸",
  },
  {
    id: "regalo-para-ti",
    tokens: ["el regalo", "es", "para ti"],
    english: "the present is for you",
    emoji: "🎁",
  },
  {
    id: "mono-platano",
    tokens: ["el mono", "come", "plátano"],
    english: "the monkey eats banana",
    emoji: "🐵",
  },
  {
    id: "abeja-pequena",
    tokens: ["la abeja", "es", "pequeña"],
    english: "the bee is small",
    emoji: "🐝",
  },
  {
    id: "tiburon-nada",
    tokens: ["el tiburón", "nada", "rápido"],
    english: "the shark swims fast",
    emoji: "🦈",
  },
  {
    id: "tortuga-lenta",
    tokens: ["la tortuga", "es", "lenta"],
    english: "the turtle is slow",
    emoji: "🐢",
  },
  {
    id: "bombero-valiente",
    tokens: ["el bombero", "es", "valiente"],
    english: "the firefighter is brave",
    emoji: "🧑‍🚒",
  },
  {
    id: "juego-futbol",
    tokens: ["yo", "juego", "al fútbol"],
    english: "I play football",
    emoji: "⚽",
  },
  {
    id: "pinguino-no-vuela",
    tokens: ["el pingüino", "no", "vuela"],
    english: "the penguin does not fly",
    emoji: "🐧",
  },
  {
    id: "arana-ocho-patas",
    tokens: ["la araña", "tiene", "ocho", "patas"],
    english: "the spider has eight legs",
    emoji: "🕷️",
  },
  {
    id: "conejo-salta",
    tokens: ["el conejo", "salta", "mucho"],
    english: "the rabbit jumps a lot",
    emoji: "🐰",
  },
  {
    id: "reina-castillo",
    tokens: ["la reina", "vive", "en el castillo"],
    english: "the queen lives in the castle",
    emoji: "👸",
  },
  {
    id: "quiero-helado",
    tokens: ["yo", "quiero", "un helado"],
    english: "I want an ice cream",
    emoji: "🍦",
  },
  {
    id: "astronauta-luna",
    tokens: ["el astronauta", "va", "a la luna"],
    english: "the astronaut goes to the moon",
    emoji: "🧑‍🚀",
  },
];
