import type { Sentence } from "../domain/sentence";

/**
 * The built-in beginner sentences: subject + verb + complement, three tiles
 * each, reusing pack vocabulary wherever possible so the words are familiar.
 */
export const SENTENCE_PACK: readonly Sentence[] = [
  {
    id: "gato-negro",
    tokens: ["el gato", "es", "negro"],
    english: "the cat is black",
    emoji: "🐱",
  },
  {
    id: "rana-verde",
    tokens: ["la rana", "es", "verde"],
    english: "the frog is green",
    emoji: "🐸",
  },
  {
    id: "elefante-grande",
    tokens: ["el elefante", "es", "grande"],
    english: "the elephant is big",
    emoji: "🐘",
  },
  {
    id: "manzana-roja",
    tokens: ["la manzana", "es", "roja"],
    english: "the apple is red",
    emoji: "🍎",
  },
  {
    id: "platano-amarillo",
    tokens: ["el plátano", "es", "amarillo"],
    english: "the banana is yellow",
    emoji: "🍌",
  },
  {
    id: "mariposa-bonita",
    tokens: ["la mariposa", "es", "bonita"],
    english: "the butterfly is pretty",
    emoji: "🦋",
  },
  {
    id: "perro-pan",
    tokens: ["el perro", "come", "pan"],
    english: "the dog eats bread",
    emoji: "🐶",
  },
  {
    id: "gato-leche",
    tokens: ["el gato", "bebe", "leche"],
    english: "the cat drinks milk",
    emoji: "🥛",
  },
  {
    id: "vaca-hierba",
    tokens: ["la vaca", "come", "hierba"],
    english: "the cow eats grass",
    emoji: "🐮",
  },
  {
    id: "pez-nada",
    tokens: ["el pez", "nada", "rápido"],
    english: "the fish swims fast",
    emoji: "🐟",
  },
  {
    id: "caballo-corre",
    tokens: ["el caballo", "corre", "rápido"],
    english: "the horse runs fast",
    emoji: "🐴",
  },
  {
    id: "pajaro-alto",
    tokens: ["el pájaro", "vuela", "alto"],
    english: "the bird flies high",
    emoji: "🐦",
  },
  {
    id: "sol-amarillo",
    tokens: ["el sol", "es", "amarillo"],
    english: "the sun is yellow",
    emoji: "☀️",
  },
  {
    id: "nieve-blanca",
    tokens: ["la nieve", "es", "blanca"],
    english: "the snow is white",
    emoji: "❄️",
  },
  {
    id: "mar-azul",
    tokens: ["el mar", "es", "azul"],
    english: "the sea is blue",
    emoji: "🌊",
  },
  {
    id: "veo-luna",
    tokens: ["yo", "veo", "la luna"],
    english: "I see the moon",
    emoji: "🌙",
  },
  {
    id: "coche-rapido",
    tokens: ["el coche", "es", "rápido"],
    english: "the car is fast",
    emoji: "🚗",
  },
  {
    id: "tren-grande",
    tokens: ["el tren", "es", "grande"],
    english: "the train is big",
    emoji: "🚂",
  },
  {
    id: "avion-alto",
    tokens: ["el avión", "vuela", "alto"],
    english: "the airplane flies high",
    emoji: "✈️",
  },
  {
    id: "camiseta-roja",
    tokens: ["la camiseta", "es", "roja"],
    english: "the t-shirt is red",
    emoji: "👕",
  },
  {
    id: "mano-pequena",
    tokens: ["la mano", "es", "pequeña"],
    english: "the hand is small",
    emoji: "🖐️",
  },
  {
    id: "duermo-cama",
    tokens: ["yo", "duermo", "en la cama"],
    english: "I sleep in the bed",
    emoji: "🛏️",
  },
  {
    id: "lluvia-fria",
    tokens: ["la lluvia", "es", "fría"],
    english: "the rain is cold",
    emoji: "🌧️",
  },
  {
    id: "helado-frio",
    tokens: ["el helado", "es", "frío"],
    english: "the ice cream is cold",
    emoji: "🍦",
  },
  {
    id: "arbol-verde",
    tokens: ["el árbol", "es", "verde"],
    english: "the tree is green",
    emoji: "🌳",
  },
  {
    id: "fuego-caliente",
    tokens: ["el fuego", "es", "caliente"],
    english: "the fire is hot",
    emoji: "🔥",
  },
  {
    id: "montana-alta",
    tokens: ["la montaña", "es", "alta"],
    english: "the mountain is tall",
    emoji: "⛰️",
  },
  {
    id: "juego-pelota",
    tokens: ["yo", "juego", "con la pelota"],
    english: "I play with the ball",
    emoji: "⚽",
  },
  {
    id: "robot-baila",
    tokens: ["el robot", "baila", "bien"],
    english: "the robot dances well",
    emoji: "🤖",
  },
  {
    id: "leo-libro",
    tokens: ["yo", "leo", "el libro"],
    english: "I read the book",
    emoji: "📕",
  },
  {
    id: "estoy-feliz",
    tokens: ["yo", "estoy", "feliz"],
    english: "I am happy",
    emoji: "😀",
  },
  {
    id: "gato-dormido",
    tokens: ["el gato", "está", "dormido"],
    english: "the cat is asleep",
    emoji: "😴",
  },
  {
    id: "toco-guitarra",
    tokens: ["yo", "toco", "la guitarra"],
    english: "I play the guitar",
    emoji: "🎸",
  },
  {
    id: "nado-mar",
    tokens: ["yo", "nado", "en el mar"],
    english: "I swim in the sea",
    emoji: "🌊",
  },
  {
    id: "flor-bonita",
    tokens: ["la flor", "es", "bonita"],
    english: "the flower is pretty",
    emoji: "🌸",
  },
  {
    id: "regalo-para-ti",
    tokens: ["el regalo", "es", "para ti"],
    english: "the present is for you",
    emoji: "🎁",
  },
  {
    id: "mono-platano",
    tokens: ["el mono", "come", "plátano"],
    english: "the monkey eats banana",
    emoji: "🐵",
  },
  {
    id: "abeja-pequena",
    tokens: ["la abeja", "es", "pequeña"],
    english: "the bee is small",
    emoji: "🐝",
  },
  {
    id: "tiburon-nada",
    tokens: ["el tiburón", "nada", "rápido"],
    english: "the shark swims fast",
    emoji: "🦈",
  },
  {
    id: "tortuga-lenta",
    tokens: ["la tortuga", "es", "lenta"],
    english: "the turtle is slow",
    emoji: "🐢",
  },
  {
    id: "bombero-valiente",
    tokens: ["el bombero", "es", "valiente"],
    english: "the firefighter is brave",
    emoji: "🧑‍🚒",
  },
  {
    id: "juego-futbol",
    tokens: ["yo", "juego", "al fútbol"],
    english: "I play football",
    emoji: "⚽",
  },
  {
    id: "pinguino-no-vuela",
    tokens: ["el pingüino", "no", "vuela"],
    english: "the penguin does not fly",
    emoji: "🐧",
  },
  {
    id: "arana-ocho-patas",
    tokens: ["la araña", "tiene", "ocho", "patas"],
    english: "the spider has eight legs",
    emoji: "🕷️",
  },
  {
    id: "conejo-salta",
    tokens: ["el conejo", "salta", "mucho"],
    english: "the rabbit jumps a lot",
    emoji: "🐰",
  },
  {
    id: "reina-castillo",
    tokens: ["la reina", "vive", "en el castillo"],
    english: "the queen lives in the castle",
    emoji: "👸",
  },
  {
    id: "quiero-helado",
    tokens: ["yo", "quiero", "un helado"],
    english: "I want an ice cream",
    emoji: "🍦",
  },
  {
    id: "astronauta-luna",
    tokens: ["el astronauta", "va", "a la luna"],
    english: "the astronaut goes to the moon",
    emoji: "🧑‍🚀",
  },
  {
    id: "vivo-ciudad",
    tokens: ["yo", "vivo", "en la ciudad"],
    english: "I live in the city",
    emoji: "🏢",
  },
  {
    id: "semaforo-rojo",
    tokens: ["el semáforo", "es", "rojo"],
    english: "the traffic light is red",
    emoji: "🚦",
  },
  {
    id: "torre-alta",
    tokens: ["la torre", "es", "alta"],
    english: "the tower is tall",
    emoji: "🗼",
  },
  {
    id: "voy-tienda",
    tokens: ["yo", "voy", "a la tienda"],
    english: "I go to the shop",
    emoji: "🏪",
  },
  {
    id: "tren-puente",
    tokens: ["el tren", "cruza", "el puente"],
    english: "the train crosses the bridge",
    emoji: "🌉",
  },
  {
    id: "fuente-agua",
    tokens: ["la fuente", "tiene", "agua"],
    english: "the fountain has water",
    emoji: "⛲",
  },
  {
    id: "mi-casa-bonita",
    tokens: ["mi casa", "es", "bonita"],
    english: "my house is pretty",
    emoji: "🏡",
  },
  {
    id: "medica-hospital",
    tokens: ["la médica", "trabaja", "en el hospital"],
    english: "the doctor works at the hospital",
    emoji: "🏥",
  },
  {
    id: "juego-parque",
    tokens: ["yo", "juego", "en el parque"],
    english: "I play in the park",
    emoji: "🛝",
  },
  {
    id: "banco-cerrado",
    tokens: ["el banco", "está", "cerrado"],
    english: "the bank is closed",
    emoji: "🏦",
  },
  {
    id: "tienda-abierta",
    tokens: ["la tienda", "está", "abierta"],
    english: "the shop is open",
    emoji: "🏪",
  },
  {
    id: "autobus-ciudad",
    tokens: ["el autobús", "va", "a la ciudad"],
    english: "the bus goes to the city",
    emoji: "🚌",
  },
  {
    id: "delfin-salta",
    tokens: ["el delfín", "salta", "alto"],
    english: "the dolphin jumps high",
    emoji: "🐬",
  },
  {
    id: "cangrejo-lado",
    tokens: ["el cangrejo", "camina", "de lado"],
    english: "the crab walks sideways",
    emoji: "🦀",
  },
  {
    id: "foca-pescado",
    tokens: ["la foca", "come", "pescado"],
    english: "the seal eats fish",
    emoji: "🦭",
  },
  {
    id: "flamenco-rosa",
    tokens: ["el flamenco", "es", "rosa"],
    english: "the flamingo is pink",
    emoji: "🦩",
  },
  {
    id: "sandia-grande",
    tokens: ["la sandía", "es", "grande"],
    english: "the watermelon is big",
    emoji: "🍉",
  },
  {
    id: "limon-acido",
    tokens: ["el limón", "es", "ácido"],
    english: "the lemon is sour",
    emoji: "🍋",
  },
  {
    id: "uva-pequena",
    tokens: ["la uva", "es", "pequeña"],
    english: "the grape is small",
    emoji: "🍇",
  },
  {
    id: "pina-dulce",
    tokens: ["la piña", "es", "dulce"],
    english: "the pineapple is sweet",
    emoji: "🍍",
  },
  {
    id: "toco-piano",
    tokens: ["yo", "toco", "el piano"],
    english: "I play the piano",
    emoji: "🎹",
  },
  {
    id: "trompeta-fuerte",
    tokens: ["la trompeta", "suena", "fuerte"],
    english: "the trumpet sounds loud",
    emoji: "🎺",
  },
  {
    id: "gusta-musica",
    tokens: ["me gusta", "la música"],
    english: "I like music",
    emoji: "🎵",
  },
  {
    id: "gusta-helado",
    tokens: ["me gusta", "el helado"],
    english: "I like ice cream",
    emoji: "🍦",
  },
  {
    id: "perro-marron",
    tokens: ["el perro", "es", "marrón"],
    english: "the dog is brown",
    emoji: "🐶",
  },
  {
    id: "oso-grande",
    tokens: ["el oso", "es", "grande"],
    english: "the bear is big",
    emoji: "🐻",
  },
  {
    id: "pez-azul",
    tokens: ["el pez", "es", "azul"],
    english: "the fish is blue",
    emoji: "🐟",
  },
  {
    id: "leon-fuerte",
    tokens: ["el león", "es", "fuerte"],
    english: "the lion is strong",
    emoji: "🦁",
  },
  {
    id: "luna-blanca",
    tokens: ["la luna", "es", "blanca"],
    english: "the moon is white",
    emoji: "🌙",
  },
  {
    id: "tren-rapido",
    tokens: ["el tren", "es", "rápido"],
    english: "the train is fast",
    emoji: "🚂",
  },
  {
    id: "raton-pequeno",
    tokens: ["el ratón", "es", "pequeño"],
    english: "the mouse is small",
    emoji: "🐭",
  },
  {
    id: "zorro-naranja",
    tokens: ["el zorro", "es", "naranja"],
    english: "the fox is orange",
    emoji: "🦊",
  },
  {
    id: "loro-verde",
    tokens: ["el loro", "es", "verde"],
    english: "the parrot is green",
    emoji: "🦜",
  },
  {
    id: "pato-amarillo",
    tokens: ["el pato", "es", "amarillo"],
    english: "the duck is yellow",
    emoji: "🦆",
  },
  {
    id: "caballo-marron",
    tokens: ["el caballo", "es", "marrón"],
    english: "the horse is brown",
    emoji: "🐴",
  },
  {
    id: "gato-gris",
    tokens: ["el gato", "es", "gris"],
    english: "the cat is grey",
    emoji: "🐱",
  },
];
