import type { Deck } from "../domain/deck";

/**
 * The built-in beginner vocabulary. Nouns carry their article so the
 * spoken form teaches gender along with the word.
 */
export const STARTER_PACK: readonly Deck[] = [
  {
    id: "animals",
    nameSpanish: "Los animales",
    nameEnglish: "Animals",
    emoji: "🐶",
    cards: [
      { id: "perro", spanish: "el perro", english: "the dog", emoji: "🐶" },
      { id: "gato", spanish: "el gato", english: "the cat", emoji: "🐱" },
      { id: "pajaro", spanish: "el pájaro", english: "the bird", emoji: "🐦" },
      { id: "pez", spanish: "el pez", english: "the fish", emoji: "🐟" },
      { id: "caballo", spanish: "el caballo", english: "the horse", emoji: "🐴" },
      { id: "vaca", spanish: "la vaca", english: "the cow", emoji: "🐮" },
      { id: "cerdo", spanish: "el cerdo", english: "the pig", emoji: "🐷" },
      { id: "pollo", spanish: "el pollo", english: "the chicken", emoji: "🐔" },
      { id: "rana", spanish: "la rana", english: "the frog", emoji: "🐸" },
      { id: "leon", spanish: "el león", english: "the lion", emoji: "🦁" },
      { id: "elefante", spanish: "el elefante", english: "the elephant", emoji: "🐘" },
      { id: "mariposa", spanish: "la mariposa", english: "the butterfly", emoji: "🦋" },
    ],
  },
  {
    id: "colors",
    nameSpanish: "Los colores",
    nameEnglish: "Colors",
    emoji: "🌈",
    cards: [
      { id: "rojo", spanish: "rojo", english: "red", emoji: "🔴" },
      { id: "naranja-color", spanish: "naranja", english: "orange", emoji: "🟠" },
      { id: "amarillo", spanish: "amarillo", english: "yellow", emoji: "🟡" },
      { id: "verde", spanish: "verde", english: "green", emoji: "🟢" },
      { id: "azul", spanish: "azul", english: "blue", emoji: "🔵" },
      { id: "morado", spanish: "morado", english: "purple", emoji: "🟣" },
      { id: "rosa", spanish: "rosa", english: "pink", emoji: "🌸" },
      { id: "marron", spanish: "marrón", english: "brown", emoji: "🟤" },
      { id: "negro", spanish: "negro", english: "black", emoji: "⚫" },
      { id: "blanco", spanish: "blanco", english: "white", emoji: "⚪" },
    ],
  },
  {
    id: "numbers",
    nameSpanish: "Los números 1–10",
    nameEnglish: "Numbers 1–10",
    emoji: "🔢",
    cards: [
      { id: "uno", spanish: "uno", english: "one", emoji: "1️⃣" },
      { id: "dos", spanish: "dos", english: "two", emoji: "2️⃣" },
      { id: "tres", spanish: "tres", english: "three", emoji: "3️⃣" },
      { id: "cuatro", spanish: "cuatro", english: "four", emoji: "4️⃣" },
      { id: "cinco", spanish: "cinco", english: "five", emoji: "5️⃣" },
      { id: "seis", spanish: "seis", english: "six", emoji: "6️⃣" },
      { id: "siete", spanish: "siete", english: "seven", emoji: "7️⃣" },
      { id: "ocho", spanish: "ocho", english: "eight", emoji: "8️⃣" },
      { id: "nueve", spanish: "nueve", english: "nine", emoji: "9️⃣" },
      { id: "diez", spanish: "diez", english: "ten", emoji: "🔟" },
    ],
  },
  {
    id: "numbers-11-20",
    nameSpanish: "Los números 11–20",
    nameEnglish: "Numbers 11–20",
    emoji: "1️⃣1️⃣",
    cards: [
      { id: "once", spanish: "once", english: "eleven", emoji: "1️⃣1️⃣" },
      { id: "doce", spanish: "doce", english: "twelve", emoji: "1️⃣2️⃣" },
      { id: "trece", spanish: "trece", english: "thirteen", emoji: "1️⃣3️⃣" },
      { id: "catorce", spanish: "catorce", english: "fourteen", emoji: "1️⃣4️⃣" },
      { id: "quince", spanish: "quince", english: "fifteen", emoji: "1️⃣5️⃣" },
      { id: "dieciseis", spanish: "dieciséis", english: "sixteen", emoji: "1️⃣6️⃣" },
      { id: "diecisiete", spanish: "diecisiete", english: "seventeen", emoji: "1️⃣7️⃣" },
      { id: "dieciocho", spanish: "dieciocho", english: "eighteen", emoji: "1️⃣8️⃣" },
      { id: "diecinueve", spanish: "diecinueve", english: "nineteen", emoji: "1️⃣9️⃣" },
      { id: "veinte", spanish: "veinte", english: "twenty", emoji: "2️⃣0️⃣" },
    ],
  },
  {
    id: "numbers-tens",
    nameSpanish: "Las decenas",
    nameEnglish: "Tens to 100",
    emoji: "💯",
    cards: [
      { id: "diez-decena", spanish: "diez", english: "ten", emoji: "1️⃣0️⃣" },
      { id: "veinte-decena", spanish: "veinte", english: "twenty", emoji: "2️⃣0️⃣" },
      { id: "treinta", spanish: "treinta", english: "thirty", emoji: "3️⃣0️⃣" },
      { id: "cuarenta", spanish: "cuarenta", english: "forty", emoji: "4️⃣0️⃣" },
      { id: "cincuenta", spanish: "cincuenta", english: "fifty", emoji: "5️⃣0️⃣" },
      { id: "sesenta", spanish: "sesenta", english: "sixty", emoji: "6️⃣0️⃣" },
      { id: "setenta", spanish: "setenta", english: "seventy", emoji: "7️⃣0️⃣" },
      { id: "ochenta", spanish: "ochenta", english: "eighty", emoji: "8️⃣0️⃣" },
      { id: "noventa", spanish: "noventa", english: "ninety", emoji: "9️⃣0️⃣" },
      { id: "cien", spanish: "cien", english: "one hundred", emoji: "💯" },
    ],
  },
  {
    id: "food",
    nameSpanish: "La comida",
    nameEnglish: "Food",
    emoji: "🍎",
    cards: [
      { id: "manzana", spanish: "la manzana", english: "the apple", emoji: "🍎" },
      { id: "platano", spanish: "el plátano", english: "the banana", emoji: "🍌" },
      { id: "pan", spanish: "el pan", english: "the bread", emoji: "🍞" , question: "¿Es pan?" },
      { id: "leche", spanish: "la leche", english: "the milk", emoji: "🥛" , question: "¿Es leche?" },
      { id: "queso", spanish: "el queso", english: "the cheese", emoji: "🧀" , question: "¿Es queso?" },
      { id: "huevo", spanish: "el huevo", english: "the egg", emoji: "🥚" },
      { id: "fresa", spanish: "la fresa", english: "the strawberry", emoji: "🍓" },
      { id: "naranja-fruta", spanish: "la naranja", english: "the orange", emoji: "🍊" },
      { id: "zanahoria", spanish: "la zanahoria", english: "the carrot", emoji: "🥕" },
      { id: "galleta", spanish: "la galleta", english: "the cookie", emoji: "🍪" },
      { id: "agua", spanish: "el agua", english: "the water", emoji: "💧" , question: "¿Es agua?" },
      { id: "helado", spanish: "el helado", english: "the ice cream", emoji: "🍦" },
    ],
  },
  {
    id: "body",
    nameSpanish: "El cuerpo",
    nameEnglish: "The body",
    emoji: "🖐️",
    cards: [
      { id: "mano", spanish: "la mano", english: "the hand", emoji: "🖐️" },
      { id: "pie", spanish: "el pie", english: "the foot", emoji: "🦶" },
      { id: "boca", spanish: "la boca", english: "the mouth", emoji: "👄" },
      { id: "nariz", spanish: "la nariz", english: "the nose", emoji: "👃" },
      { id: "oreja", spanish: "la oreja", english: "the ear", emoji: "👂" },
      { id: "ojos", spanish: "los ojos", english: "the eyes", emoji: "👀" },
      { id: "diente", spanish: "el diente", english: "the tooth", emoji: "🦷" },
      { id: "lengua", spanish: "la lengua", english: "the tongue", emoji: "👅" },
      { id: "brazo", spanish: "el brazo", english: "the arm", emoji: "💪" },
      { id: "pierna", spanish: "la pierna", english: "the leg", emoji: "🦵" },
      { id: "corazon", spanish: "el corazón", english: "the heart", emoji: "❤️" },
      { id: "dedo", spanish: "el dedo", english: "the finger", emoji: "☝️" },
    ],
  },
  {
    id: "clothes",
    nameSpanish: "La ropa",
    nameEnglish: "Clothes",
    emoji: "👕",
    cards: [
      { id: "camiseta", spanish: "la camiseta", english: "the t-shirt", emoji: "👕" },
      { id: "pantalon", spanish: "el pantalón", english: "the pants", emoji: "👖" },
      { id: "vestido", spanish: "el vestido", english: "the dress", emoji: "👗" },
      { id: "zapato", spanish: "el zapato", english: "the shoe", emoji: "👟" },
      { id: "bota", spanish: "la bota", english: "the boot", emoji: "👢" },
      { id: "gorra", spanish: "la gorra", english: "the cap", emoji: "🧢" },
      { id: "sombrero", spanish: "el sombrero", english: "the hat", emoji: "🎩" },
      { id: "calcetines", spanish: "los calcetines", english: "the socks", emoji: "🧦" },
      { id: "abrigo", spanish: "el abrigo", english: "the coat", emoji: "🧥" },
      { id: "bufanda", spanish: "la bufanda", english: "the scarf", emoji: "🧣" },
      { id: "guantes", spanish: "los guantes", english: "the gloves", emoji: "🧤" },
      { id: "corona", spanish: "la corona", english: "the crown", emoji: "👑" },
    ],
  },
  {
    id: "house",
    nameSpanish: "La casa",
    nameEnglish: "The house",
    emoji: "🏠",
    cards: [
      { id: "cama", spanish: "la cama", english: "the bed", emoji: "🛏️" },
      { id: "sofa", spanish: "el sofá", english: "the sofa", emoji: "🛋️" },
      { id: "silla", spanish: "la silla", english: "the chair", emoji: "🪑" },
      { id: "puerta", spanish: "la puerta", english: "the door", emoji: "🚪" },
      { id: "ventana", spanish: "la ventana", english: "the window", emoji: "🪟" },
      { id: "banera", spanish: "la bañera", english: "the bathtub", emoji: "🛁" },
      { id: "inodoro", spanish: "el inodoro", english: "the toilet", emoji: "🚽" },
      { id: "llave", spanish: "la llave", english: "the key", emoji: "🔑" },
      { id: "reloj", spanish: "el reloj", english: "the clock", emoji: "⏰" },
      { id: "telefono", spanish: "el teléfono", english: "the phone", emoji: "📱" },
      { id: "television", spanish: "la televisión", english: "the television", emoji: "📺" },
      { id: "libro", spanish: "el libro", english: "the book", emoji: "📕" },
    ],
  },
  {
    id: "vehicles",
    nameSpanish: "Los vehículos",
    nameEnglish: "Vehicles",
    emoji: "🚗",
    cards: [
      { id: "coche", spanish: "el coche", english: "the car", emoji: "🚗" },
      { id: "autobus", spanish: "el autobús", english: "the bus", emoji: "🚌" },
      { id: "tren", spanish: "el tren", english: "the train", emoji: "🚂" },
      { id: "avion", spanish: "el avión", english: "the airplane", emoji: "✈️" },
      { id: "barco", spanish: "el barco", english: "the boat", emoji: "⛵" },
      { id: "bicicleta", spanish: "la bicicleta", english: "the bicycle", emoji: "🚲" },
      { id: "moto", spanish: "la moto", english: "the motorcycle", emoji: "🏍️" },
      { id: "camion", spanish: "el camión", english: "the truck", emoji: "🚚" },
      { id: "cohete", spanish: "el cohete", english: "the rocket", emoji: "🚀" },
      { id: "helicoptero", spanish: "el helicóptero", english: "the helicopter", emoji: "🚁" },
      { id: "tractor", spanish: "el tractor", english: "the tractor", emoji: "🚜" },
      { id: "ambulancia", spanish: "la ambulancia", english: "the ambulance", emoji: "🚑" },
    ],
  },
  {
    id: "weather",
    nameSpanish: "El tiempo",
    nameEnglish: "Weather",
    emoji: "⛅",
    cards: [
      { id: "sol", spanish: "el sol", english: "the sun", emoji: "☀️" , question: "¿Es el sol?" },
      { id: "luna", spanish: "la luna", english: "the moon", emoji: "🌙" , question: "¿Es la luna?" },
      { id: "estrella", spanish: "la estrella", english: "the star", emoji: "⭐" },
      { id: "nube", spanish: "la nube", english: "the cloud", emoji: "☁️" },
      { id: "lluvia", spanish: "la lluvia", english: "the rain", emoji: "🌧️" , question: "¿Es lluvia?" },
      { id: "nieve", spanish: "la nieve", english: "the snow", emoji: "❄️" , question: "¿Es nieve?" },
      { id: "viento", spanish: "el viento", english: "the wind", emoji: "💨" , question: "¿Es viento?" },
      { id: "rayo", spanish: "el rayo", english: "the lightning", emoji: "⚡" },
      { id: "arcoiris", spanish: "el arcoíris", english: "the rainbow", emoji: "🌈" },
      { id: "mar", spanish: "el mar", english: "the sea", emoji: "🌊" , question: "¿Es el mar?" },
      { id: "calor", spanish: "el calor", english: "the heat", emoji: "🥵" , question: "¿Hace calor?" },
      { id: "frio", spanish: "el frío", english: "the cold", emoji: "🥶" , question: "¿Hace frío?" },
    ],
  },
  {
    id: "school",
    nameSpanish: "El colegio",
    nameEnglish: "School",
    emoji: "🎒",
    cards: [
      { id: "lapiz", spanish: "el lápiz", english: "the pencil", emoji: "✏️" },
      { id: "cuaderno", spanish: "el cuaderno", english: "the notebook", emoji: "📓" },
      { id: "tijeras", spanish: "las tijeras", english: "the scissors", emoji: "✂️" },
      { id: "mochila", spanish: "la mochila", english: "the backpack", emoji: "🎒" },
      { id: "regla", spanish: "la regla", english: "the ruler", emoji: "📏" },
      { id: "pincel", spanish: "el pincel", english: "the paintbrush", emoji: "🖌️" },
      { id: "ordenador", spanish: "el ordenador", english: "the computer", emoji: "💻" },
      { id: "profesora", spanish: "la profesora", english: "the teacher", emoji: "👩‍🏫" },
      { id: "campana", spanish: "la campana", english: "the bell", emoji: "🔔" },
      { id: "mapa", spanish: "el mapa", english: "the map", emoji: "🗺️" },
      { id: "iman", spanish: "el imán", english: "the magnet", emoji: "🧲" },
      { id: "papel", spanish: "el papel", english: "the paper", emoji: "📜" , question: "¿Es papel?" },
    ],
  },
  {
    id: "feelings",
    nameSpanish: "Las emociones",
    nameEnglish: "Feelings",
    emoji: "😀",
    cards: [
      { id: "feliz", spanish: "feliz", english: "happy", emoji: "😀", usesEstar: true },
      { id: "triste", spanish: "triste", english: "sad", emoji: "😢", usesEstar: true },
      { id: "enfadado", spanish: "enfadado", english: "angry", emoji: "😠", usesEstar: true },
      { id: "sorprendido", spanish: "sorprendido", english: "surprised", emoji: "😮", usesEstar: true },
      { id: "asustado", spanish: "asustado", english: "scared", emoji: "😱", usesEstar: true },
      { id: "cansado", spanish: "cansado", english: "tired", emoji: "🥱", usesEstar: true },
      { id: "enfermo", spanish: "enfermo", english: "sick", emoji: "🤒", usesEstar: true },
      { id: "contento", spanish: "contento", english: "glad", emoji: "😊", usesEstar: true },
      { id: "dormido", spanish: "dormido", english: "asleep", emoji: "😴", usesEstar: true },
      { id: "aburrido", spanish: "aburrido", english: "bored", emoji: "😑", usesEstar: true },
      { id: "nervioso", spanish: "nervioso", english: "nervous", emoji: "😬", usesEstar: true },
      { id: "enamorado", spanish: "enamorado", english: "in love", emoji: "😍", usesEstar: true },
    ],
  },
  {
    id: "nature",
    nameSpanish: "La naturaleza",
    nameEnglish: "Nature",
    emoji: "🌳",
    cards: [
      { id: "arbol", spanish: "el árbol", english: "the tree", emoji: "🌳" },
      { id: "pino", spanish: "el pino", english: "the pine tree", emoji: "🌲" },
      { id: "flor", spanish: "la flor", english: "the flower", emoji: "🌸" },
      { id: "hoja", spanish: "la hoja", english: "the leaf", emoji: "🍃" },
      { id: "seta", spanish: "la seta", english: "the mushroom", emoji: "🍄" },
      { id: "cactus", spanish: "el cactus", english: "the cactus", emoji: "🌵" },
      { id: "palmera", spanish: "la palmera", english: "the palm tree", emoji: "🌴" },
      { id: "montana", spanish: "la montaña", english: "the mountain", emoji: "⛰️" },
      { id: "volcan", spanish: "el volcán", english: "the volcano", emoji: "🌋" },
      { id: "piedra", spanish: "la piedra", english: "the stone", emoji: "🪨" },
      { id: "fuego", spanish: "el fuego", english: "the fire", emoji: "🔥" , question: "¿Es fuego?" },
      { id: "playa", spanish: "la playa", english: "the beach", emoji: "🏖️" },
    ],
  },
  {
    id: "toys",
    nameSpanish: "Los juguetes",
    nameEnglish: "Toys",
    emoji: "🧸",
    cards: [
      { id: "pelota", spanish: "la pelota", english: "the ball", emoji: "⚽" },
      { id: "peluche", spanish: "el peluche", english: "the teddy", emoji: "🧸" },
      { id: "muneca", spanish: "la muñeca", english: "the doll", emoji: "🪆" },
      { id: "robot", spanish: "el robot", english: "the robot", emoji: "🤖" },
      { id: "globo", spanish: "el globo", english: "the balloon", emoji: "🎈" },
      { id: "puzle", spanish: "el puzle", english: "the puzzle", emoji: "🧩" },
      { id: "dado", spanish: "el dado", english: "the die", emoji: "🎲" },
      { id: "cometa", spanish: "la cometa", english: "the kite", emoji: "🪁" },
      { id: "tambor", spanish: "el tambor", english: "the drum", emoji: "🥁" },
      { id: "guitarra", spanish: "la guitarra", english: "the guitar", emoji: "🎸" },
      { id: "castillo", spanish: "el castillo", english: "the castle", emoji: "🏰" },
      { id: "regalo", spanish: "el regalo", english: "the present", emoji: "🎁" },
    ],
  },
  {
    id: "sports",
    nameSpanish: "Los deportes",
    nameEnglish: "Sports",
    emoji: "🏅",
    cards: [
      { id: "futbol", spanish: "el fútbol", english: "football", emoji: "⚽" , question: "¿Es fútbol?" },
      { id: "baloncesto", spanish: "el baloncesto", english: "basketball", emoji: "🏀" , question: "¿Es baloncesto?" },
      { id: "tenis", spanish: "el tenis", english: "tennis", emoji: "🎾" , question: "¿Es tenis?" },
      { id: "natacion", spanish: "la natación", english: "swimming", emoji: "🏊" , question: "¿Es natación?" },
      { id: "beisbol", spanish: "el béisbol", english: "baseball", emoji: "⚾" , question: "¿Es béisbol?" },
      { id: "voleibol", spanish: "el voleibol", english: "volleyball", emoji: "🏐" , question: "¿Es voleibol?" },
      { id: "golf", spanish: "el golf", english: "golf", emoji: "⛳" , question: "¿Es golf?" },
      { id: "esqui", spanish: "el esquí", english: "skiing", emoji: "⛷️" , question: "¿Es esquí?" },
      { id: "patinaje", spanish: "el patinaje", english: "skating", emoji: "⛸️" , question: "¿Es patinaje?" },
      { id: "ciclismo", spanish: "el ciclismo", english: "cycling", emoji: "🚴" , question: "¿Es ciclismo?" },
      { id: "medalla", spanish: "la medalla", english: "the medal", emoji: "🏅" },
      { id: "trofeo", spanish: "el trofeo", english: "the trophy", emoji: "🏆" },
    ],
  },
  {
    id: "bugs",
    nameSpanish: "Los bichos",
    nameEnglish: "Bugs",
    emoji: "🐝",
    cards: [
      { id: "abeja", spanish: "la abeja", english: "the bee", emoji: "🐝" },
      { id: "hormiga", spanish: "la hormiga", english: "the ant", emoji: "🐜" },
      { id: "arana", spanish: "la araña", english: "the spider", emoji: "🕷️" },
      { id: "caracol", spanish: "el caracol", english: "the snail", emoji: "🐌" },
      { id: "mariquita", spanish: "la mariquita", english: "the ladybug", emoji: "🐞" },
      { id: "gusano", spanish: "el gusano", english: "the worm", emoji: "🪱" },
      { id: "mosquito", spanish: "el mosquito", english: "the mosquito", emoji: "🦟" },
      { id: "mosca", spanish: "la mosca", english: "the fly", emoji: "🪰" },
      { id: "saltamontes", spanish: "el saltamontes", english: "the grasshopper", emoji: "🦗" },
      { id: "escarabajo", spanish: "el escarabajo", english: "the beetle", emoji: "🪲" },
      { id: "escorpion", spanish: "el escorpión", english: "the scorpion", emoji: "🦂" },
      { id: "telarana", spanish: "la telaraña", english: "the spiderweb", emoji: "🕸️" },
    ],
  },
  {
    id: "zoo",
    nameSpanish: "El zoo",
    nameEnglish: "The zoo",
    emoji: "🐵",
    cards: [
      { id: "mono", spanish: "el mono", english: "the monkey", emoji: "🐵" },
      { id: "oso", spanish: "el oso", english: "the bear", emoji: "🐻" },
      { id: "pinguino", spanish: "el pingüino", english: "the penguin", emoji: "🐧" },
      { id: "tiburon", spanish: "el tiburón", english: "the shark", emoji: "🦈" },
      { id: "ballena", spanish: "la ballena", english: "the whale", emoji: "🐳" },
      { id: "pulpo", spanish: "el pulpo", english: "the octopus", emoji: "🐙" },
      { id: "tortuga", spanish: "la tortuga", english: "the turtle", emoji: "🐢" },
      { id: "serpiente", spanish: "la serpiente", english: "the snake", emoji: "🐍" },
      { id: "conejo", spanish: "el conejo", english: "the rabbit", emoji: "🐰" },
      { id: "raton", spanish: "el ratón", english: "the mouse", emoji: "🐭" },
      { id: "jirafa", spanish: "la jirafa", english: "the giraffe", emoji: "🦒" },
      { id: "zorro", spanish: "el zorro", english: "the fox", emoji: "🦊" },
    ],
  },
  {
    id: "jobs",
    nameSpanish: "Las profesiones",
    nameEnglish: "Jobs",
    emoji: "🧑‍🚒",
    cards: [
      { id: "bombero", spanish: "el bombero", english: "the firefighter", emoji: "🧑‍🚒" },
      { id: "medica", spanish: "la médica", english: "the doctor", emoji: "👩‍⚕️" },
      { id: "policia", spanish: "el policía", english: "the police officer", emoji: "👮" },
      { id: "cocinera", spanish: "la cocinera", english: "the cook", emoji: "👩‍🍳" },
      { id: "astronauta", spanish: "el astronauta", english: "the astronaut", emoji: "🧑‍🚀" },
      { id: "cientifica", spanish: "la científica", english: "the scientist", emoji: "👩‍🔬" },
      { id: "granjero", spanish: "el granjero", english: "the farmer", emoji: "🧑‍🌾" },
      { id: "artista", spanish: "la artista", english: "the artist", emoji: "👩‍🎨" },
      { id: "piloto", spanish: "el piloto", english: "the pilot", emoji: "🧑‍✈️" },
      { id: "cantante", spanish: "la cantante", english: "the singer", emoji: "👩‍🎤" },
      { id: "mago", spanish: "el mago", english: "the magician", emoji: "🧙" },
      { id: "reina", spanish: "la reina", english: "the queen", emoji: "👸" },
    ],
  },
  {
    id: "city",
    nameSpanish: "La ciudad",
    nameEnglish: "The city",
    emoji: "🏙️",
    cards: [
      { id: "semaforo", spanish: "el semáforo", english: "the traffic light", emoji: "🚦" },
      { id: "tienda", spanish: "la tienda", english: "the shop", emoji: "🏪" },
      { id: "hospital", spanish: "el hospital", english: "the hospital", emoji: "🏥" },
      { id: "banco", spanish: "el banco", english: "the bank", emoji: "🏦" },
      { id: "iglesia", spanish: "la iglesia", english: "the church", emoji: "⛪" },
      { id: "puente", spanish: "el puente", english: "the bridge", emoji: "🌉" },
      { id: "torre", spanish: "la torre", english: "the tower", emoji: "🗼" },
      { id: "fuente", spanish: "la fuente", english: "the fountain", emoji: "⛲" },
      { id: "edificio", spanish: "el edificio", english: "the building", emoji: "🏢" },
      { id: "fabrica", spanish: "la fábrica", english: "the factory", emoji: "🏭" },
      { id: "carretera", spanish: "la carretera", english: "the road", emoji: "🛣️" },
      { id: "casa", spanish: "la casa", english: "the house", emoji: "🏡" },
    ],
  },
  {
    id: "sea",
    nameSpanish: "El mar",
    nameEnglish: "The sea",
    emoji: "🦀",
    cards: [
      { id: "cangrejo", spanish: "el cangrejo", english: "the crab", emoji: "🦀" },
      { id: "gamba", spanish: "la gamba", english: "the shrimp", emoji: "🦐" },
      { id: "calamar", spanish: "el calamar", english: "the squid", emoji: "🦑" },
      { id: "foca", spanish: "la foca", english: "the seal", emoji: "🦭" },
      { id: "delfin", spanish: "el delfín", english: "the dolphin", emoji: "🐬" },
      { id: "coral", spanish: "el coral", english: "the coral", emoji: "🪸", question: "¿Es coral?" },
      { id: "concha", spanish: "la concha", english: "the seashell", emoji: "🐚" },
      { id: "pez-payaso", spanish: "el pez payaso", english: "the clownfish", emoji: "🐠" },
      { id: "pez-globo", spanish: "el pez globo", english: "the pufferfish", emoji: "🐡" },
      { id: "cocodrilo", spanish: "el cocodrilo", english: "the crocodile", emoji: "🐊" },
      { id: "nutria", spanish: "la nutria", english: "the otter", emoji: "🦦" },
      { id: "flamenco", spanish: "el flamenco", english: "the flamingo", emoji: "🦩" },
    ],
  },
  {
    id: "fruit",
    nameSpanish: "La fruta",
    nameEnglish: "Fruit",
    emoji: "🍉",
    cards: [
      { id: "pera", spanish: "la pera", english: "the pear", emoji: "🍐" },
      { id: "uva", spanish: "la uva", english: "the grape", emoji: "🍇" },
      { id: "sandia", spanish: "la sandía", english: "the watermelon", emoji: "🍉" },
      { id: "melon", spanish: "el melón", english: "the melon", emoji: "🍈" },
      { id: "pina", spanish: "la piña", english: "the pineapple", emoji: "🍍" },
      { id: "melocoton", spanish: "el melocotón", english: "the peach", emoji: "🍑" },
      { id: "cereza", spanish: "la cereza", english: "the cherry", emoji: "🍒" },
      { id: "limon", spanish: "el limón", english: "the lemon", emoji: "🍋" },
      { id: "kiwi", spanish: "el kiwi", english: "the kiwi", emoji: "🥝" },
      { id: "coco", spanish: "el coco", english: "the coconut", emoji: "🥥" },
      { id: "mango", spanish: "el mango", english: "the mango", emoji: "🥭" },
      { id: "aguacate", spanish: "el aguacate", english: "the avocado", emoji: "🥑" },
    ],
  },
  {
    id: "music",
    nameSpanish: "La música",
    nameEnglish: "Music",
    emoji: "🎵",
    cards: [
      { id: "piano", spanish: "el piano", english: "the piano", emoji: "🎹" },
      { id: "violin", spanish: "el violín", english: "the violin", emoji: "🎻" },
      { id: "trompeta", spanish: "la trompeta", english: "the trumpet", emoji: "🎺" },
      { id: "saxofon", spanish: "el saxofón", english: "the saxophone", emoji: "🎷" },
      { id: "flauta", spanish: "la flauta", english: "the flute", emoji: "🪈" },
      { id: "acordeon", spanish: "el acordeón", english: "the accordion", emoji: "🪗" },
      { id: "banjo", spanish: "el banjo", english: "the banjo", emoji: "🪕" },
      { id: "microfono", spanish: "el micrófono", english: "the microphone", emoji: "🎤" },
      { id: "auriculares", spanish: "los auriculares", english: "the headphones", emoji: "🎧" },
      { id: "radio", spanish: "la radio", english: "the radio", emoji: "📻" },
      { id: "musica", spanish: "la música", english: "the music", emoji: "🎵", question: "¿Es música?" },
      { id: "partitura", spanish: "la partitura", english: "the sheet music", emoji: "🎼" },
    ],
  },
  // Los verbos — action words, one deck per verb form. Learn-only: the games
  // build noun-shaped questions ("¿Es un…?") that don't fit a verb, so these
  // are flashcards-only. All three forms teach the same 12 verbs, same order,
  // same pictures — only the spoken form changes.
  {
    id: "verbs-infinitive",
    nameSpanish: "El infinitivo",
    nameEnglish: "Verbs: infinitive",
    emoji: "🔤",
    learnOnly: true,
    cards: [
      { id: "comer", spanish: "comer", english: "to eat", emoji: "🍽️" },
      { id: "dormir", spanish: "dormir", english: "to sleep", emoji: "😴" },
      { id: "correr", spanish: "correr", english: "to run", emoji: "🏃" },
      { id: "saltar", spanish: "saltar", english: "to jump", emoji: "🦘" },
      { id: "jugar", spanish: "jugar", english: "to play", emoji: "⚽" },
      { id: "cantar", spanish: "cantar", english: "to sing", emoji: "🎤" },
      { id: "leer", spanish: "leer", english: "to read", emoji: "📖" },
      { id: "beber", spanish: "beber", english: "to drink", emoji: "🥤" },
      { id: "llorar", spanish: "llorar", english: "to cry", emoji: "😭" },
      { id: "reir", spanish: "reír", english: "to laugh", emoji: "😂" },
      { id: "caminar", spanish: "caminar", english: "to walk", emoji: "🚶" },
      { id: "bailar", spanish: "bailar", english: "to dance", emoji: "💃" },
    ],
  },
  {
    id: "verbs-gerund",
    nameSpanish: "El gerundio",
    nameEnglish: "Verbs: -ing",
    emoji: "⏳",
    learnOnly: true,
    cards: [
      { id: "comiendo", spanish: "comiendo", english: "eating", emoji: "🍽️" },
      { id: "durmiendo", spanish: "durmiendo", english: "sleeping", emoji: "😴" },
      { id: "corriendo", spanish: "corriendo", english: "running", emoji: "🏃" },
      { id: "saltando", spanish: "saltando", english: "jumping", emoji: "🦘" },
      { id: "jugando", spanish: "jugando", english: "playing", emoji: "⚽" },
      { id: "cantando", spanish: "cantando", english: "singing", emoji: "🎤" },
      { id: "leyendo", spanish: "leyendo", english: "reading", emoji: "📖" },
      { id: "bebiendo", spanish: "bebiendo", english: "drinking", emoji: "🥤" },
      { id: "llorando", spanish: "llorando", english: "crying", emoji: "😭" },
      { id: "riendo", spanish: "riendo", english: "laughing", emoji: "😂" },
      { id: "caminando", spanish: "caminando", english: "walking", emoji: "🚶" },
      { id: "bailando", spanish: "bailando", english: "dancing", emoji: "💃" },
    ],
  },
  {
    id: "verbs-imperative",
    nameSpanish: "El imperativo",
    nameEnglish: "Verbs: commands",
    emoji: "📣",
    learnOnly: true,
    cards: [
      { id: "come", spanish: "¡come!", english: "eat!", emoji: "🍽️" },
      { id: "duerme", spanish: "¡duerme!", english: "sleep!", emoji: "😴" },
      { id: "corre", spanish: "¡corre!", english: "run!", emoji: "🏃" },
      { id: "salta", spanish: "¡salta!", english: "jump!", emoji: "🦘" },
      { id: "juega", spanish: "¡juega!", english: "play!", emoji: "⚽" },
      { id: "canta", spanish: "¡canta!", english: "sing!", emoji: "🎤" },
      { id: "lee", spanish: "¡lee!", english: "read!", emoji: "📖" },
      { id: "bebe", spanish: "¡bebe!", english: "drink!", emoji: "🥤" },
      { id: "llora", spanish: "¡llora!", english: "cry!", emoji: "😭" },
      { id: "rie", spanish: "¡ríe!", english: "laugh!", emoji: "😂" },
      { id: "camina", spanish: "¡camina!", english: "walk!", emoji: "🚶" },
      { id: "baila", spanish: "¡baila!", english: "dance!", emoji: "💃" },
    ],
  },
  {
    id: "mystery",
    nameSpanish: "El misterio",
    nameEnglish: "Mystery",
    emoji: "🔮",
    secret: true,
    unlockCost: 100,
    cards: [
      { id: "fantasma", spanish: "el fantasma", english: "the ghost", emoji: "👻" },
      { id: "vampiro", spanish: "el vampiro", english: "the vampire", emoji: "🧛" },
      { id: "zombi", spanish: "el zombi", english: "the zombie", emoji: "🧟" },
      { id: "ogro", spanish: "el ogro", english: "the ogre", emoji: "👹" },
      { id: "duende", spanish: "el duende", english: "the goblin", emoji: "👺" },
      { id: "genio", spanish: "el genio", english: "the genie", emoji: "🧞" },
      { id: "hada", spanish: "el hada", english: "the fairy", emoji: "🧚" },
      { id: "calavera", spanish: "la calavera", english: "the skull", emoji: "💀" },
      { id: "diamante", spanish: "el diamante", english: "the diamond", emoji: "💎" },
      { id: "bola-magica", spanish: "la bola mágica", english: "the magic ball", emoji: "🔮" },
      { id: "murcielago", spanish: "el murciélago", english: "the bat", emoji: "🦇" },
      { id: "vela", spanish: "la vela", english: "the candle", emoji: "🕯️" },
    ],
  },
];
