import type { Deck } from "../domain/deck";

/**
 * The built-in beginner vocabulary. Nouns carry their article so the
 * spoken form teaches gender along with the word.
 */
export const STARTER_PACK: readonly Deck[] = [
  {
    id: "animals",
    nameSpanish: "Los animales",
    nameEnglish: "Animals",
    emoji: "🐶",
    cards: [
      { id: "perro", spanish: "el perro", english: "the dog", emoji: "🐶" },
      { id: "gato", spanish: "el gato", english: "the cat", emoji: "🐱" },
      { id: "pajaro", spanish: "el pájaro", english: "the bird", emoji: "🐦" },
      { id: "pez", spanish: "el pez", english: "the fish", emoji: "🐟" },
      { id: "caballo", spanish: "el caballo", english: "the horse", emoji: "🐴" },
      { id: "vaca", spanish: "la vaca", english: "the cow", emoji: "🐮" },
      { id: "cerdo", spanish: "el cerdo", english: "the pig", emoji: "🐷" },
      { id: "pollo", spanish: "el pollo", english: "the chicken", emoji: "🐔" },
      { id: "rana", spanish: "la rana", english: "the frog", emoji: "🐸" },
      { id: "leon", spanish: "el león", english: "the lion", emoji: "🦁" },
      { id: "elefante", spanish: "el elefante", english: "the elephant", emoji: "🐘" },
      { id: "mariposa", spanish: "la mariposa", english: "the butterfly", emoji: "🦋" },
    ],
  },
  {
    id: "colors",
    nameSpanish: "Los colores",
    nameEnglish: "Colors",
    emoji: "🌈",
    cards: [
      { id: "rojo", spanish: "rojo", english: "red", emoji: "🔴" },
      { id: "naranja-color", spanish: "naranja", english: "orange", emoji: "🟠" },
      { id: "amarillo", spanish: "amarillo", english: "yellow", emoji: "🟡" },
      { id: "verde", spanish: "verde", english: "green", emoji: "🟢" },
      { id: "azul", spanish: "azul", english: "blue", emoji: "🔵" },
      { id: "morado", spanish: "morado", english: "purple", emoji: "🟣" },
      { id: "rosa", spanish: "rosa", english: "pink", emoji: "🌸" },
      { id: "marron", spanish: "marrón", english: "brown", emoji: "🟤" },
      { id: "negro", spanish: "negro", english: "black", emoji: "⚫" },
      { id: "blanco", spanish: "blanco", english: "white", emoji: "⚪" },
    ],
  },
  {
    id: "numbers",
    nameSpanish: "Los números 1–10",
    nameEnglish: "Numbers 1–10",
    emoji: "🔢",
    cards: [
      { id: "uno", spanish: "uno", english: "one", emoji: "1️⃣" },
      { id: "dos", spanish: "dos", english: "two", emoji: "2️⃣" },
      { id: "tres", spanish: "tres", english: "three", emoji: "3️⃣" },
      { id: "cuatro", spanish: "cuatro", english: "four", emoji: "4️⃣" },
      { id: "cinco", spanish: "cinco", english: "five", emoji: "5️⃣" },
      { id: "seis", spanish: "seis", english: "six", emoji: "6️⃣" },
      { id: "siete", spanish: "siete", english: "seven", emoji: "7️⃣" },
      { id: "ocho", spanish: "ocho", english: "eight", emoji: "8️⃣" },
      { id: "nueve", spanish: "nueve", english: "nine", emoji: "9️⃣" },
      { id: "diez", spanish: "diez", english: "ten", emoji: "🔟" },
    ],
  },
  {
    id: "numbers-11-20",
    nameSpanish: "Los números 11–20",
    nameEnglish: "Numbers 11–20",
    emoji: "1️⃣1️⃣",
    cards: [
      { id: "once", spanish: "once", english: "eleven", emoji: "1️⃣1️⃣" },
      { id: "doce", spanish: "doce", english: "twelve", emoji: "1️⃣2️⃣" },
      { id: "trece", spanish: "trece", english: "thirteen", emoji: "1️⃣3️⃣" },
      { id: "catorce", spanish: "catorce", english: "fourteen", emoji: "1️⃣4️⃣" },
      { id: "quince", spanish: "quince", english: "fifteen", emoji: "1️⃣5️⃣" },
      { id: "dieciseis", spanish: "dieciséis", english: "sixteen", emoji: "1️⃣6️⃣" },
      { id: "diecisiete", spanish: "diecisiete", english: "seventeen", emoji: "1️⃣7️⃣" },
      { id: "dieciocho", spanish: "dieciocho", english: "eighteen", emoji: "1️⃣8️⃣" },
      { id: "diecinueve", spanish: "diecinueve", english: "nineteen", emoji: "1️⃣9️⃣" },
      { id: "veinte", spanish: "veinte", english: "twenty", emoji: "2️⃣0️⃣" },
    ],
  },
  {
    id: "numbers-tens",
    nameSpanish: "Las decenas",
    nameEnglish: "Tens to 100",
    emoji: "💯",
    cards: [
      { id: "diez-decena", spanish: "diez", english: "ten", emoji: "1️⃣0️⃣" },
      { id: "veinte-decena", spanish: "veinte", english: "twenty", emoji: "2️⃣0️⃣" },
      { id: "treinta", spanish: "treinta", english: "thirty", emoji: "3️⃣0️⃣" },
      { id: "cuarenta", spanish: "cuarenta", english: "forty", emoji: "4️⃣0️⃣" },
      { id: "cincuenta", spanish: "cincuenta", english: "fifty", emoji: "5️⃣0️⃣" },
      { id: "sesenta", spanish: "sesenta", english: "sixty", emoji: "6️⃣0️⃣" },
      { id: "setenta", spanish: "setenta", english: "seventy", emoji: "7️⃣0️⃣" },
      { id: "ochenta", spanish: "ochenta", english: "eighty", emoji: "8️⃣0️⃣" },
      { id: "noventa", spanish: "noventa", english: "ninety", emoji: "9️⃣0️⃣" },
      { id: "cien", spanish: "cien", english: "one hundred", emoji: "💯" },
    ],
  },
  {
    id: "food",
    nameSpanish: "La comida",
    nameEnglish: "Food",
    emoji: "🍎",
    cards: [
      { id: "manzana", spanish: "la manzana", english: "the apple", emoji: "🍎" },
      { id: "platano", spanish: "el plátano", english: "the banana", emoji: "🍌" },
      { id: "pan", spanish: "el pan", english: "the bread", emoji: "🍞" },
      { id: "leche", spanish: "la leche", english: "the milk", emoji: "🥛" },
      { id: "queso", spanish: "el queso", english: "the cheese", emoji: "🧀" },
      { id: "huevo", spanish: "el huevo", english: "the egg", emoji: "🥚" },
      { id: "fresa", spanish: "la fresa", english: "the strawberry", emoji: "🍓" },
      { id: "naranja-fruta", spanish: "la naranja", english: "the orange", emoji: "🍊" },
      { id: "zanahoria", spanish: "la zanahoria", english: "the carrot", emoji: "🥕" },
      { id: "galleta", spanish: "la galleta", english: "the cookie", emoji: "🍪" },
      { id: "agua", spanish: "el agua", english: "the water", emoji: "💧" },
      { id: "helado", spanish: "el helado", english: "the ice cream", emoji: "🍦" },
    ],
  },
  {
    id: "body",
    nameSpanish: "El cuerpo",
    nameEnglish: "The body",
    emoji: "🖐️",
    cards: [
      { id: "mano", spanish: "la mano", english: "the hand", emoji: "🖐️" },
      { id: "pie", spanish: "el pie", english: "the foot", emoji: "🦶" },
      { id: "boca", spanish: "la boca", english: "the mouth", emoji: "👄" },
      { id: "nariz", spanish: "la nariz", english: "the nose", emoji: "👃" },
      { id: "oreja", spanish: "la oreja", english: "the ear", emoji: "👂" },
      { id: "ojos", spanish: "los ojos", english: "the eyes", emoji: "👀" },
      { id: "diente", spanish: "el diente", english: "the tooth", emoji: "🦷" },
      { id: "lengua", spanish: "la lengua", english: "the tongue", emoji: "👅" },
      { id: "brazo", spanish: "el brazo", english: "the arm", emoji: "💪" },
      { id: "pierna", spanish: "la pierna", english: "the leg", emoji: "🦵" },
      { id: "corazon", spanish: "el corazón", english: "the heart", emoji: "❤️" },
      { id: "dedo", spanish: "el dedo", english: "the finger", emoji: "☝️" },
    ],
  },
  {
    id: "clothes",
    nameSpanish: "La ropa",
    nameEnglish: "Clothes",
    emoji: "👕",
    cards: [
      { id: "camiseta", spanish: "la camiseta", english: "the t-shirt", emoji: "👕" },
      { id: "pantalon", spanish: "el pantalón", english: "the pants", emoji: "👖" },
      { id: "vestido", spanish: "el vestido", english: "the dress", emoji: "👗" },
      { id: "zapato", spanish: "el zapato", english: "the shoe", emoji: "👟" },
      { id: "bota", spanish: "la bota", english: "the boot", emoji: "👢" },
      { id: "gorra", spanish: "la gorra", english: "the cap", emoji: "🧢" },
      { id: "sombrero", spanish: "el sombrero", english: "the hat", emoji: "🎩" },
      { id: "calcetines", spanish: "los calcetines", english: "the socks", emoji: "🧦" },
      { id: "abrigo", spanish: "el abrigo", english: "the coat", emoji: "🧥" },
      { id: "bufanda", spanish: "la bufanda", english: "the scarf", emoji: "🧣" },
      { id: "guantes", spanish: "los guantes", english: "the gloves", emoji: "🧤" },
      { id: "corona", spanish: "la corona", english: "the crown", emoji: "👑" },
    ],
  },
  {
    id: "house",
    nameSpanish: "La casa",
    nameEnglish: "The house",
    emoji: "🏠",
    cards: [
      { id: "cama", spanish: "la cama", english: "the bed", emoji: "🛏️" },
      { id: "sofa", spanish: "el sofá", english: "the sofa", emoji: "🛋️" },
      { id: "silla", spanish: "la silla", english: "the chair", emoji: "🪑" },
      { id: "puerta", spanish: "la puerta", english: "the door", emoji: "🚪" },
      { id: "ventana", spanish: "la ventana", english: "the window", emoji: "🪟" },
      { id: "banera", spanish: "la bañera", english: "the bathtub", emoji: "🛁" },
      { id: "inodoro", spanish: "el inodoro", english: "the toilet", emoji: "🚽" },
      { id: "llave", spanish: "la llave", english: "the key", emoji: "🔑" },
      { id: "reloj", spanish: "el reloj", english: "the clock", emoji: "⏰" },
      { id: "telefono", spanish: "el teléfono", english: "the phone", emoji: "📱" },
      { id: "television", spanish: "la televisión", english: "the television", emoji: "📺" },
      { id: "libro", spanish: "el libro", english: "the book", emoji: "📕" },
    ],
  },
  {
    id: "vehicles",
    nameSpanish: "Los vehículos",
    nameEnglish: "Vehicles",
    emoji: "🚗",
    cards: [
      { id: "carro", spanish: "el carro", english: "the car", emoji: "🚗" },
      { id: "autobus", spanish: "el autobús", english: "the bus", emoji: "🚌" },
      { id: "tren", spanish: "el tren", english: "the train", emoji: "🚂" },
      { id: "avion", spanish: "el avión", english: "the airplane", emoji: "✈️" },
      { id: "barco", spanish: "el barco", english: "the boat", emoji: "⛵" },
      { id: "bicicleta", spanish: "la bicicleta", english: "the bicycle", emoji: "🚲" },
      { id: "moto", spanish: "la moto", english: "the motorcycle", emoji: "🏍️" },
      { id: "camion", spanish: "el camión", english: "the truck", emoji: "🚚" },
      { id: "cohete", spanish: "el cohete", english: "the rocket", emoji: "🚀" },
      { id: "helicoptero", spanish: "el helicóptero", english: "the helicopter", emoji: "🚁" },
      { id: "tractor", spanish: "el tractor", english: "the tractor", emoji: "🚜" },
      { id: "ambulancia", spanish: "la ambulancia", english: "the ambulance", emoji: "🚑" },
    ],
  },
  {
    id: "weather",
    nameSpanish: "El clima",
    nameEnglish: "Weather",
    emoji: "⛅",
    cards: [
      { id: "sol", spanish: "el sol", english: "the sun", emoji: "☀️" },
      { id: "luna", spanish: "la luna", english: "the moon", emoji: "🌙" },
      { id: "estrella", spanish: "la estrella", english: "the star", emoji: "⭐" },
      { id: "nube", spanish: "la nube", english: "the cloud", emoji: "☁️" },
      { id: "lluvia", spanish: "la lluvia", english: "the rain", emoji: "🌧️" },
      { id: "nieve", spanish: "la nieve", english: "the snow", emoji: "❄️" },
      { id: "viento", spanish: "el viento", english: "the wind", emoji: "💨" },
      { id: "rayo", spanish: "el rayo", english: "the lightning", emoji: "⚡" },
      { id: "arcoiris", spanish: "el arcoíris", english: "the rainbow", emoji: "🌈" },
      { id: "mar", spanish: "el mar", english: "the sea", emoji: "🌊" },
      { id: "calor", spanish: "el calor", english: "the heat", emoji: "🥵" },
      { id: "frio", spanish: "el frío", english: "the cold", emoji: "🥶" },
    ],
  },
];
